### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by abhisrkckl** [ymaan4/rfiClean#4]
Can you please add a few lines about how to install and configure the package in the README file?

**Comment by macrocosme** [comment]
Yes, we will look into it. Thank you for the input.

**Comment by ymaan4** [comment]
A standard `Makefile` is included in the package which means installing could be as simple as running `make`, that is why no installation/configuration instructions were included earlier. A section named "_Installation_" and a few things in the `Makefile` which might need user's attention are now included in the README file. Hope that helps.

**Comment by abhisrkckl** [comment]
Thanks.. It is very helpful.
