### ISSUE TITLE
Hardcoded paths in crp_rficlean_gm.sh

### ISSUE THREAD

**Issue by abhisrkckl** [ymaan4/rfiClean#9]
The absolute path of the rficlean executable (/home/ymaan/bin/rficlean) is hardcoded in crp_rficlean_gm.sh.
crp_rficlean_gm.sh fails in a new installation due to this.

**Comment by ymaan4** [comment]
This was on the radar and will be fixed very soon along with a merge of OpenMP branch. Thanks for bringing it up though.

**Comment by ymaan4** [comment]
Fixed. Now 'rficlean' should be in the user's PATH.

**Comment by abhisrkckl** [comment]
Thanks.
